version: "3.2"
services:
  redis:
    image: redis:3.0.7
    container_name: backend-redis
    ports:
      - "6353:6379"
    networks:
      - webnet
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    container_name: backend
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    networks:
      - webnet
networks:
  webnet:
