# Create a version of Alpine with the necessary requirements
FROM alpine:3.7

ENV LIBRARY_PATH=/lib:/usr/lib

# Install dependencies to build python modules.
# In particular, Pillow, ldap, and psycopg_2.
RUN apk update && \
    apk add python3


COPY requirements.txt requirements.txt

RUN python3 -m pip install -r requirements.txt --no-cache-dir

WORKDIR /code/
